In [1]:
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

print(text[0:50])



First Citizen:
Before we proceed any further, hear


In [2]:
chars = sorted(set(text))

stoi = { ch:i for i, ch in enumerate(chars)}
itos = {i:ch for i, ch in enumerate(chars)}
encode = lambda s: [stoi[c] for c in s]
decode = lambda l: ''.join([itos[i] for i in l])
print(encode("I love going to the park"))
print(decode(encode("I love going to the park")))

[21, 1, 50, 53, 60, 43, 1, 45, 53, 47, 52, 45, 1, 58, 53, 1, 58, 46, 43, 1, 54, 39, 56, 49]
I love going to the park


In [9]:
import torch
idx = torch.zeros((1,1))
for _ in range(10):

            idx_cond = idx[:, -8:]

            
            idx_next = torch.ones((1, 1))
            idx = torch.cat((idx, idx_next), dim=1)

print(idx)    
print(idx.shape)

tensor([[0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
torch.Size([1, 11])


In [ ]:
e = dict()
print(len(chars))
for i in range(len(chars)):
    e[chars[i]] = i
print(e['\n'])
d = dict()
i = 0
for c in chars:
    d[i] = c
    i += 1

def encoder(input):
    output = []
    
    for c in input:
        output.append(e[c])

    return output

o = encoder("\n !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz")
print(o)

In [ ]:
for i in range(3):
    print(i)

In [4]:
import torch
import torch.nn as nn
import numpy as np

with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()


chars = sorted(list(set(text)))
stoi = { ch:i for i, ch in enumerate(chars)}
itos = {i:ch for i, ch in enumerate(chars)}
encode = lambda s: [stoi[c] for c in s]
decode = lambda l: ''.join([itos[i] for i in l])

torch.manual_seed(1337)
block_size = 8
batch_size = 4
vocab_size = len(chars)

data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data))
train_data = data[:n]
val_data = data[n:]

def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+1+block_size] for i in ix])
    return x, y

xb, yb = get_batch('train')
ebed = nn.Embedding(59, 59)





data = train_data
ix = torch.randint(len(data) - block_size, (batch_size,))
x = torch.stack([data[i:i+block_size] for i in ix])
y = torch.stack([data[i+1:i+1+block_size] for i in ix])
print(ix.shape)
print(data.shape)
print(x.shape)


torch.Size([4])
torch.Size([1003854])
torch.Size([4, 8])


In [ ]:
torch.cuda.is_available()

In [ ]:
ebed = nn.Embedding(100, 50)
x = torch.tensor([[1,1,1],[2,2,2]])
print(x.data)
out = ebed(x)
print(out)
print(out.shape)

In [87]:
torch.manual_seed(1337)
B,T,C = 4, 8, 2
x = torch.randn(B, T, C)
xbow = torch.zeros(B, T, C)

for b in range(B):
    for t in range(T):
        xprev = x[b, :t+1]
        xbow[b, t] = torch.mean(xprev, 0)

print(xbow[0])

tensor([[ 0.1808, -0.0700],
        [-0.0894, -0.4926],
        [ 0.1490, -0.3199],
        [ 0.3504, -0.2238],
        [ 0.3525,  0.0545],
        [ 0.0688, -0.0396],
        [ 0.0927, -0.0682],
        [-0.0341,  0.1332]])


In [ ]:
torch.manual_seed(1337)
T = 8
x = torch.randn(T, T)
t1 = torch.tril(torch.zeros(T, T))
t2 = torch.tril(torch.ones(T, T))
x1 = x.masked_fill(t1 == 0, float('-inf'))
x2 = x.masked_fill(t2==0, float('-inf'))

print(t1)
print(t2)
print(x1)
print(x2)

            


tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])
tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])
tensor([[-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -in

In [30]:
import torch
import torch.nn as nn
from torch.nn import functional as F
block_size = 8
batch_size = 8
max_iters = 3000
eval_interval = 300
learning_rate = 1e-2
ebed_size = 32
device = "cuda"
eval_iters = 200
head_size = 8

In [49]:
query = nn.Linear(ebed_size, head_size, bias=False, device=device)
key = nn.Linear(ebed_size, head_size, bias=False, device=device)
value = nn.Linear(ebed_size, head_size, bias=False, device=device)
ffn = nn.Linear(ebed_size, vocab_size)
layer_norm = nn.LayerNorm(ebed_size)

input = torch.randn((batch_size, block_size, ebed_size)).to(device) /5
print("input shape:", input.shape) # 10, 8, 32

B, T, C = input.shape  #batch size, sequence length, feature dimentionality
logitsList = []    
for _ in range(int(ebed_size/head_size)):
        Q = query(input)
        print("Q, shape:", Q.shape)  #10, 8, 12
        K = key(input)
        V = value(input)
        attn = torch.matmul(Q, K.transpose(-2, -1)) * C**-0.5  # (8x12 @ 12x8), 8x8
        print("attn shape:", attn.shape)
        tril = torch.tril(torch.zeros(T, T)).to(device)

            
        attn = attn.masked_fill(tril == 0, float('-inf'))
        logit = F.softmax(attn, dim=1) @ V   #10x8x8 @ 10x8x12
        logitsList.append(logit)

print(torch.Tensor(torch.concat(logitsList, dim=-1)).shape)



input shape: torch.Size([8, 8, 32])
Q, shape: torch.Size([8, 8, 8])
attn shape: torch.Size([8, 8, 8])
Q, shape: torch.Size([8, 8, 8])
attn shape: torch.Size([8, 8, 8])
Q, shape: torch.Size([8, 8, 8])
attn shape: torch.Size([8, 8, 8])
Q, shape: torch.Size([8, 8, 8])
attn shape: torch.Size([8, 8, 8])
torch.Size([8, 8, 32])


In [47]:
a = torch.arange(0,12).reshape(2,2,3)
print(a)
torch.concat([a, a], dim=-1)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])


tensor([[[ 0,  1,  2,  0,  1,  2],
         [ 3,  4,  5,  3,  4,  5]],

        [[ 6,  7,  8,  6,  7,  8],
         [ 9, 10, 11,  9, 10, 11]]])

In [10]:
import torch
import torch.nn as nn
from torch.nn import functional as F
import math
import torch.optim as optim

torch.manual_seed(1337)
block_size = 16
batch_size = 4
max_iters = 3000
eval_interval = 300
learning_rate = 1e-2
ebed_size = 64
device = "cuda"
eval_iters = 200
head_size = 8


with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()


chars = sorted(list(set(text)))
stoi = { ch:i for i, ch in enumerate(chars)}
itos = {i:ch for i, ch in enumerate(chars)}
encode = lambda s: [stoi[c] for c in s]
decode = lambda l: ''.join([itos[i] for i in l])
vocab_size = len(chars)

data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data))
train_data = data[:n]
val_data = data[n:]


x = train_data[:block_size]
y = train_data[1:block_size+1]



def get_batch(split):
    data = train_data if split == 'train' else val_data
    # Ensure we don't go out of bounds
    ix = torch.randint(len(data) - block_size - 1, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix]).to(device)
    y = torch.stack([data[i+1:i+1+block_size] for i in ix]).to(device)
    
    return x, y

@torch.no_grad()
def estimate_loss(model):
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()

        out[split] = losses.mean()
    model.train()
    return out

class DecoderBlock(nn.Module):
    def __init__(self, ebed_size, head_size):
        super().__init__()
        self.multi_head = MultiHead(ebed_size, head_size)
        self.ffn = nn.Sequential(nn.Linear(ebed_size, 4 * ebed_size), 
                                  nn.ReLU(),
                                  nn.Linear(4*ebed_size, ebed_size))

    def forward(self, input):
        out = self.multi_head(input)
        out = self.ffn(out)        
        return out  

class MultiHead(nn.Module):
    def __init__(self, ebed_size, head_size):
        super().__init__()
        self.att_head = nn.ModuleList(AttHead(ebed_size, head_size) for _ in range(int(ebed_size/head_size)))
        self.proj = nn.Linear(ebed_size, ebed_size)
        
    def forward(self, input):
        out = torch.concat([head(input) for head in self.att_head], dim=-1)
        out = self.proj(out)
        return out


class AttHead(nn.Module):

    def __init__(self, ebed_size, head_size):
        super().__init__()
        self.query = nn.Linear(ebed_size, head_size, bias=False, device=device)
        self.key = nn.Linear(ebed_size, head_size, bias=False, device=device)
        self.value = nn.Linear(ebed_size, head_size, bias=False, device=device)
        
    def forward(self, input):
        
        B, T, C = input.shape  #batch size, sequence length, feature dimentionality
        Q = self.query(input)  #4x16x64  -> 4x16x8
        K = self.key(input)
        V = self.value(input)
        attn = torch.matmul(Q, K.transpose(-2, -1)) * C**-0.5  # 4x16x8 @ 4x8x16 -> 4x16x16
        tril = torch.tril(torch.zeros(T, T)).to(device)
                
        attn = attn.masked_fill(tril == 0, float('-inf'))
        logits = F.softmax(attn, dim=1) @ V  # 4x16x16 @ 4x16x8 -> 4x16x8
            
        return logits

class nanoGPT(nn.Module):

    def __init__(self, vocab_size, ebed_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, ebed_size).to(device)
        self.pos_embedding_table = nn.Embedding(block_size, ebed_size).to(device)
        self.db = DecoderBlock(ebed_size, head_size)
        self.final = nn.Linear(ebed_size, vocab_size)

    def forward(self, idx, targets=None):

        tok_emb = self.token_embedding_table(idx)
        pos_emb = self.pos_embedding_table(torch.arange(block_size, device=device))
        input = tok_emb + pos_emb
        
        if targets is None:
            loss = None
        else:
            logits = self.db(input)
            logits = self.final(logits)
            B, T, C = logits.shape 
            logits = logits.view(B*T, C)  
            
            targets = targets.view(B*T).to(device)
            
            # Before computing loss:
            loss = F.cross_entropy(logits, targets).to(device)
            

        return logits, loss

    def generate(self, idx, max_new_tokens):

        for _ in range(max_new_tokens):

            idx_cond = idx[:, -block_size:]

            logits, loss = self(idx_cond)
            logits = logits[:, -1, :]
            probs = F.softmax(logits, dim=-1)
            idx_next = torch.multinomial(probs, num_samples=1)
            idx = torch.cat((idx, idx_next), dim=1)

        return idx
    

model = nanoGPT(vocab_size, ebed_size).to(device)

xb, yb = get_batch('train')                        # 确保数据在 GPU 上
print(next(model.parameters()).device)              # 应输出 "cuda:0"
print(xb.device)




cuda:0
cuda:0


In [11]:
import torch
print(torch.cuda.is_available())  # 应输出 True
print(torch.cuda.current_device())  # 应输出 0（或其他有效 GPU 索引）

True
0


In [13]:
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'  # 在代码开头添加
print(os.environ.get('CUDA_VISIBLE_DEVICES'))  # 应输出至少一个 GPU 索引（如 "0"）

0
