In [2]:
import torch

In [37]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(X)
print(Y)
X<Y

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])


tensor([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]])

In [66]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(4).reshape((1, 4))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1, 2, 3]]))

In [67]:
a+b

tensor([[0, 1, 2, 3],
        [1, 2, 3, 4],
        [2, 3, 4, 5]])

In [72]:


X = torch.arange(24).reshape((3, 4, 2))
Y = torch.arange(8).reshape((1, 4, 2))
X += Y
print(X)
print(X.shape)





tensor([[[ 0,  2],
         [ 4,  6],
         [ 8, 10],
         [12, 14]],

        [[ 8, 10],
         [12, 14],
         [16, 18],
         [20, 22]],

        [[16, 18],
         [20, 22],
         [24, 26],
         [28, 30]]])
torch.Size([3, 4, 2])


In [19]:
A = torch.randn((2, 3, 4))
print(A.sum(axis=0).shape)
print(A.sum(axis=1).shape)
print(A.sum(axis=2).shape)
print(len(A))

torch.Size([3, 4])
torch.Size([2, 4])
torch.Size([2, 3])
2
